### ISSUE TITLE
Errors prevented startup

### ISSUE THREAD

**Issue by dayjimenez** [huttonr/bootstrap3#16]
Hello and thanks for your work on bootstrap 3 with less for meteor. i recently removed twbs:bootstrap from my meteor app so that i could add in your bootstrap package that uses less.  after following the steps i read on [stackoverflow](http://stackoverflow.com/questions/22070973/how-to-update-bootstrap-and-use-less-in-a-meteor-app) (although i couldn't get past the -sed step), when my app runs it gives the following error:

```
=> Errors prevented startup:

   While processing files with huttonr:bootstrap3 (for target web.browser):
   native: Unexpected token /
   at Object.parse (native)
   at plugin/bootstrap3.js:140:25
   at BootstrapCompiler.processFilesForTarget (plugin/bootstrap3.js:342:9)


=> Your application has errors. Waiting for file change.
```

Not sure if this is an issue with your package or with my setup, but hoping you can help. sorry if something stupid, I'm still new with Meteor and Bootstrap.

**Comment by huttonr** [comment]
The stackoverflow article you referenced is very old and is not applicable to current Meteor versions.

I don't mind assisting.  What version of Meteor are you running and what OS?

**Comment by huttonr** [comment]
@dayjimenez 
Is this still an issue for you?
