### ISSUE TITLE
`exists` / `existsSync` have been deprecated in Node/Meteor

### ISSUE THREAD

**Issue by abernix** [huttonr/bootstrap3#20]
Your package will cease to work when Meteor 1.3.3 is released because [the `exists` and `existsSync` methods have been deprecated in Node](https://nodejs.org/dist/latest-v4.x/docs/api/fs.html#fs_fs_existssync_path) and will need to be changed to use `access` / `accessSync`.  Meteor is deprecating these methods to facilitate upgrading its own Node version (currently pre-v4, but upgrading soon).

I came here to open this issue because of [this comment](https://github.com/meteor/meteor/pull/7033#issuecomment-223219092) in the Meteor 1.3.3 beta release thread.

**Comment by huttonr** [comment]
@abernix 

Thank you for the heads-up Jesse.

I have now fixed this with [huttonr:bootstrap3@3.3.6_11](https://github.com/huttonr/bootstrap3/commit/d7187f0127303938a8be4668acf17da4ace04991)

However it appears that `Plugin.fs` now gives only a small subset of the functions available to `fs` and it does _not_ seem to give `fs.access` or `fs.accessSync`.  This seems to be an error?  I will post an issue proper but this was one of the issues I ran into (hence the hack-ey open/close tactic).

**Comment by abernix** [comment]
Correct – it does not.  I'm not in a place to check more thoroughly right now, but I believe the intention is to provide less and less access directly from Meteor and encourage package authors to use the `fs` npm package directly if they need it.  If you find issues doing so, please do open an issue at meteor/meteor! :smile:
