### ISSUE TITLE
Heads Up: fs.existsSync will be removed in Meteor 1.3.3 / 1.4

### ISSUE THREAD

**Issue by JesperWe** [huttonr/bootstrap3#21]
https://github.com/nodejs/node/issues/1592

...so this package will need an update.

**Comment by huttonr** [comment]
Thank you for submitting this.

This is now fixed with [huttonr:bootstrap3@3.3.6_11](https://github.com/huttonr/bootstrap3/commit/d7187f0127303938a8be4668acf17da4ace04991)
