### ISSUE TITLE
Bootstrap loaded after custom less files.  How to reorder?

### ISSUE THREAD

**Issue by MichaelJCole** [huttonr/bootstrap3#24]
Hi, Meteor 1.3 is creating a /merged-stylesheets.css with my custom less files first, then the bootstrap files.

How can I load bootstrap first? 

```
./client/bootstrap-settings.json
./client/bootstrap_variables.less
./client/**/*.less
```

Thanks!

**Comment by MichaelJCole** [comment]
Ok, fussed with it and did this:

```
./client/lib/bootstrap-settings.json
./client/lib/bootstrap_variables.less
./client/**/*.less
```

The bootstrap less seems to load first now.  Thanks for the great package :-)

**Comment by Philip-Nunoo** [comment]
@MichaelJCole you solution didn't seem to fix my issue here. Running on meteor1.4

**Comment by MichaelJCole** [comment]
@Philip-Nunoo hmmm... I'd recommend opening a new issue.  This may have changed in 1.4
