### ISSUE TITLE
Errors prevented startup

### ISSUE THREAD

**Issue by marktomm** [huttonr/bootstrap3#8]
Hello!

I made a minimalist meteor project (meteor create ...) added this package and created an empty file 'bootstrap-settings.json' in 'client/lib' (tried 'client'  also) and meteor fails to start.

```
=> Errors prevented startup:                  

   While processing files with huttonr:bootstrap3 (for target web.browser):
   error: ENOENT, open 'client/lib/bootstrap-settings.json'

=> Your application has errors. Waiting for file change.

```

I'm running Ubuntu 14.04.3 LTS

Meteor 1.2.1

meteor list:
autopublish           1.0.4  (For prototyping only) Publish the entire database to all clients
blaze-html-templates  1.0.1  Compile HTML templates into reactive UI with Meteor Blaze
ecmascript            0.1.6\* Compiler plugin that supports ES2015+ in all .js files
es5-shim              4.1.14  Shims and polyfills to improve ECMAScript 5 support
huttonr:bootstrap3    3.3.6_3  Modular, customizable Bootstrap 3.
insecure              1.0.4  (For prototyping only) Allow all database writes from the client
jquery                1.11.4  Manipulate the DOM using CSS selectors
meteor-base           1.0.1  Packages that every Meteor app needs
mobile-experience     1.0.1  Packages for a great mobile user experience
mongo                 1.1.3  Adaptor for using MongoDB and Minimongo over DDP
session               1.1.1  Session variable
standard-minifiers    1.0.2  Standard minifiers used with Meteor apps by default.
tracker               1.0.9  Dependency tracker to allow reactive callbacks

[Reproduction](https://github.com/marktomm/huttonr-bootstrap3-bug-repr)

**Comment by huttonr** [comment]
The reproduction runs fine on my Fedora machine.

Is there a permissions issue on yours?

**Comment by huttonr** [comment]
@marktomm 
Is this still an issue with `huttonr:bootstrap3@3.3.6_6` on `METEOR@1.2.1`?

**Comment by marktomm** [comment]
@huttonr 
Will retest everything today. (Sry been busy lately)

**Comment by marktomm** [comment]
Everything is OK now.

Thank You!
