### ISSUE TITLE
Further extend readme

### ISSUE THREAD

**Issue by hegelstad** [huttonr/bootstrap3#9]
I am a new to using source code and compiling it, only used precompiled bootstrap before. I would appreciate a quick start guide in the readme on how to use bootstrap with less on meteor.

**Comment by OptimusCrime** [comment]
:+1:

**Comment by huttonr** [comment]
Please let me know if this is now enough for you:

https://github.com/huttonr/bootstrap3/blob/master/README.md

**Comment by hegelstad** [comment]
Super!! thanks.
